# Default values for sink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: akhilak/sink
  tag: latest
  pullPolicy: IfNotPresent
  repo: akhilak/darkstat
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
#serivce port value for sink service
  type: NodePort
  ports:
    port: 667
    nodePort: 30667

nodeSelector: {}

tolerations: []

affinity: {}
