apiVersion: v1
kind: OnapNetwork
metadata:
  name: ovn-priv-net
spec:
  config: '{
	  "cnitype": "ovn4nfvk8s",
	  "name": "mynet",
	  "subnet": "172.16.33.0/24",
	  "gateway": "172.16.33.1",
	  "routes": [{
		  "dst": "172.16.29.1/24",
		  "gw": "100.64.1.1"
	  }]
  }'